=== theuaniyo/Pruebas_Imp-Exp/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="gestor_gtd">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bandeja_entrada" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="lista_tareas_simples" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="mis_proyectos" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="usuario" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="bandeja_entrada">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tarea_entrada" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tarea_entrada">
    <xs:complexType>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="lista_tareas_simples">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tarea_simple" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tarea_simple">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contexto" type="xs:string" minOccurs="0"/>
        <xs:element name="anotacion" type="xs:string" minOccurs="0"/>
        <xs:element name="complejidad" type="xs:string" minOccurs="0"/>
        <xs:element name="requisitos" type="xs:string" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="mis_proyectos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="proyecto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="proyecto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lista_tareas" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="fecha_fin" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="lista_tareas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tarea_proyecto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tarea_proyecto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="prioridad" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="dependencia" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fecha_fin">
    <xs:complexType>
      <xs:attribute name="fecha" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== theuaniyo/Pruebas_Imp-Exp/esquema_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestor_gtd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" usuario="" xsi:noNamespaceSchemaLocation="esquema.xsd">
  <bandeja_entrada>
    <tarea_entrada nombre=""/>
    <!-- ... -->
  </bandeja_entrada>
  <lista_tareas_simples>
    <tarea_simple nombre="">
      <contexto>un contexto</contexto>
      <anotacion>una anotacion</anotacion>
      <complejidad>una complejidad</complejidad>
      <requisitos>un requisito</requisitos>
    </tarea_simple>
    <!-- ... -->
  </lista_tareas_simples>
  <mis_proyectos>
    <proyecto nombre="">
      <lista_tareas>
        <tarea_proyecto>
          <prioridad>una prioridad</prioridad>
          <dependencia>unaTareaProyecto</dependencia>
        </tarea_proyecto>
        <!-- ... -->
      </lista_tareas>
      <fecha_fin fecha=""/>
    </proyecto>
    <!-- ... -->
  </mis_proyectos>
</gestor_gtd>
